-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 15:54:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JolieBoite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JolieBoite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JolieBoite` DEFAULT CHARACTER SET utf8 ;
USE `JolieBoite` ;

-- -----------------------------------------------------
-- Table `JolieBoite`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JolieBoite`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `nomUtilisateur` VARCHAR(55) NOT NULL,
  `mdp` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JolieBoite`.`Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JolieBoite`.`Entreprise` (
  `idEntreprise` INT NOT NULL,
  `nomEntreprise` VARCHAR(55) NOT NULL,
  `numSiret` INT NOT NULL,
  `adressePostale` VARCHAR(255) NOT NULL,
  `codePostal` VARCHAR(55) NOT NULL,
  `ville` VARCHAR(55) NOT NULL,
  `descriptionEntreprise` TEXT(2004) NULL,
  `url` TEXT(2004) NULL,
  `Utilisateur_idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idEntreprise`),
  INDEX `fk_Entreprise_Utilisateur1_idx` (`Utilisateur_idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Entreprise_Utilisateur1`
    FOREIGN KEY (`Utilisateur_idUtilisateur`)
    REFERENCES `JolieBoite`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JolieBoite`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JolieBoite`.`Contact` (
  `idContact` INT NOT NULL,
  `nomContact` VARCHAR(55) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `poste` VARCHAR(45) NULL,
  `telephone` VARCHAR(10) NULL,
  `statut` VARCHAR(45) NOT NULL,
  `Entreprise_idEntreprise` INT NOT NULL,
  PRIMARY KEY (`idContact`),
  INDEX `fk_Contact_Entreprise_idx` (`Entreprise_idEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Contact_Entreprise`
    FOREIGN KEY (`Entreprise_idEntreprise`)
    REFERENCES `JolieBoite`.`Entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JolieBoite`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JolieBoite`.`Commentaire` (
  `idCommentaire` INT NOT NULL,
  `descriptionCommentaire` TEXT(2004) NOT NULL,
  `auteur` VARCHAR(55) NOT NULL,
  `date_de_creation` DATE NOT NULL,
  `Contact_idContact` INT NOT NULL,
  PRIMARY KEY (`idCommentaire`),
  INDEX `fk_Commentaire_Contact1_idx` (`Contact_idContact` ASC) VISIBLE,
  CONSTRAINT `fk_Commentaire_Contact1`
    FOREIGN KEY (`Contact_idContact`)
    REFERENCES `JolieBoite`.`Contact` (`idContact`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
